### ISSUE TITLE
Talk Proposal: Getting Started with Docker and Node

### ISSUE THREAD

**Issue by JoeDoyle23** [sfnode/discuss#1]
**Getting Started with Docker and Node**

Running applications using Docker has become increasingly popular over the last year. All the hype can make it hard to determine if Docker would be valuable to your infrastructure and workflow. We'll dive into the basics of Docker and containers with a focus on hosting Node.js applications. From there we'll walk through the basics on how to build and run your app in a container, and how to scale up using Docker. I'll also share my tips and tricks picked up from running containers in production.

**About Joe Doyle**
Joe Doyle is Head of Server for App Press where does Node.js development building out the core product as well as playing devops guy managing the infrastructure. In a past life he was a .NET developer and Windows administrator in the mid-west.

**Comment by dshaw** [comment]
@JoeDoyle23 Thank you!

**Comment by dshaw** [comment]
http://www.meetup.com/sfnode/events/223133402/
